heat_template_version: 2018-08-31

description: template (????????????)

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      # key_name: cc2024
      key_name: batashev
      # name: batashev
      image: ubuntu-20.04
      flavor: m1.small
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: "17eae9b6-2168-4a07-a0d3-66d5ad2a9f0e"
